### ISSUE TITLE
Fused-BN

### ISSUE THREAD

**Issue by kaishijeng** [Zehaos/MobileNet#10]
I saw inference time will be faster if Fused-BN is on. How do I turn it on?
Thanks

**Comment by Zehaos** [comment]
[pull 5](https://github.com/Zehaos/MobileNet/pull/5)

**Comment by kaishijeng** [comment]
Will this fused-bn help inference time (forward)?

Thanks,

**Comment by Zehaos** [comment]
Fused bn accelerate both forward and backward, please go to the first two line of the benchmark table.
