### ISSUE TITLE
Is in your code after conv first relu then bn?

### ISSUE THREAD

**Issue by andongchen** [Zehaos/MobileNet#11]
In your depthwise_separable function
`  def _depthwise_separable_conv(inputs,
                                num_pwc_filters,
                                width_multiplier,
                                sc,
                                downsample=False):
    """ Helper function to build the depth-wise separable convolution layer.
    """
    num_pwc_filters = round(num_pwc_filters * width_multiplier)
    _stride = 2 if downsample else 1

    # skip pointwise by setting num_outputs=None
    depthwise_conv = slim.separable_convolution2d(inputs,
                                                  num_outputs=None,
                                                  stride=_stride,
                                                  depth_multiplier=1,
                                                  kernel_size=[3, 3],
                                                  scope=sc+'/depthwise_conv')

    bn = slim.batch_norm(depthwise_conv, scope=sc+'/dw_batch_norm')
    pointwise_conv = slim.convolution2d(bn,
                                        num_pwc_filters,
                                        kernel_size=[1, 1],
                                        scope=sc+'/pointwise_conv')
    bn = slim.batch_norm(pointwise_conv, scope=sc+'/pw_batch_norm')
    return bn`
After executed slim.separable_convolutin2d() then will execute relu activation function!So in your code is first execute relu activation function and then execute slim.batch_norm.
But in moblilenet paper is first execute BN and then relu!

**Comment by Zehaos** [comment]
Please refer to [issue #7](https://github.com/Zehaos/MobileNet/issues/7).
