### ISSUE TITLE
error in running scripts/train_mobilenetdet_on_kitti.sh

### ISSUE THREAD

**Issue by ofersa** [Zehaos/MobileNet#17]
Hi,

when trying to run scripts/train_mobilenetdet_on_kitti.sh  I'm getting 
ValueError: Cannot reshape a tensor with 7884864 elements to shape [39,12,9,2] (8424 elements) for 'Reshape_7' (op: 'Reshape') with input shapes: [1971216,4], [4] and with input tensors computed as partial shapes: input[1] = [39,12,9,2].

please advice,
Ofer

**Comment by Zehaos** [comment]
Hi, Ofer

The detection part is still under developing.

**Comment by ofersa** [comment]
Thanks,

any ETA for that part ?

Ofer

**Comment by Zehaos** [comment]
It depends. Thanks.

**Comment by mustafa-qamaruddin** [comment]
Is it still under development?
ValueError: Dimension size must be evenly divisible by 25272 but is 5292 for 'Interpre_prediction/pred_class_probs' (op: 'Reshape') with input shapes: [882,6], [3] and with input tensors computed as partial shapes: input[1] = [?,4212,6].
