### ISSUE TITLE
Fused Batch-Norm导致量化后的模型 inference时奔溃

### ISSUE THREAD

**Issue by YAMLONG** [Zehaos/MobileNet#21]
Hi，
感谢你们提供的代码和模型，我刚刚用你们提供的model在flowers数据集上 fine tune该model时打开了Fused Batch-Norm，fine tune后的模型在量化之后inference时程序奔溃，出现以下错误：
tensorflow.python.framework.errors_impl.InvalidArgumentError: requested_output_max must be >= requested_output_min, but got -nan and 0
[[Node: MobileNet/conv_ds_7/pointwise_conv/convolution_eightbit_requantize = Requantize[Tinput=DT_QINT32, out_type=DT_QUINT8, _device="/job:localhost/replica:0/task:0/cpu:0"](MobileNet/conv_ds_7/pointwise_conv/convolution_eightbit_quantized_conv, MobileNet/conv_ds_7/pointwise_conv/convolution_eightbit_quantized_conv:1, MobileNet/conv_ds_7/pointwise_conv/convolution_eightbit_quantized_conv:2, MobileNet/conv_ds_7/pointwise_conv/convolution_eightbit_requant_range, MobileNet/conv_ds_7/pointwise_conv/convolution_eightbit_requant_range:1)]]

请问你们是否做过Fused-BN + Quantized的相关测试？？ 或者对以上的错误有什么建议？？ 谢谢！！

**Comment by Zehaos** [comment]
你好， 我并未做过相关测试， 请向tensorflow开源社区寻求帮助。
I have never tested Fused-BN + Quantized. Please ask tf community for help.

Zehao

**Comment by Zehaos** [comment]
如果你全部使用的是我tools里面的脚本，看下是不是tensorflow版本的问题， 因为更新很快。
