### ISSUE TITLE
Problem on running train image classifier

### ISSUE THREAD

**Issue by modanesh** [Zehaos/MobileNet#28]
I'm trying to run train_image_classifier.py on MNIST dataset using CPU, but I get the below error:
```
INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.FailedPreconditionError'>, input must have 3 channels but input only has 1 channels.
	 [[Node: distort_image/distort_color_3/adjust_saturation/RGBToHSV = RGBToHSV[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](distort_image/distort_color_3/adjust_saturation/Identity)]]
```

What should I do?

**Comment by Zehaos** [comment]
Chose a right preprocess method by
```
--preprocessing_name=lenet
```

**Comment by modanesh** [comment]
Is it a proper way to validate the test set? I'm working with mnist.

`python eval_image_classifier.py \
  --checkpoint_path=${TRAIN_DIR} \
  --eval_dir=${TRAIN_DIR} \
  --dataset_name=mnist \
  --dataset_split_name=test \
  --dataset_dir=${DATASET_DIR} \
  --model_name=lenet
`

**Comment by Zehaos** [comment]
@modanesh yes

**Comment by amirjamez** [comment]
@Zehaos @modanesh  Looking at the file **models/slim/preprocessing/preprocessing_factory.py**, on the preprocessing_map is says: 
`'mobilenet_v1': inception_preprocessing,`

So why would I receive the error still when I wanna train mobilenet_v1 with MNIST? 

`python train_image_classifier.py     --train_dir=${TRAIN_DIR}     --dataset_name=mnist     --dataset_split_name=train     --dataset_dir=${DATASET_DIR} \ --model_name=mobilenet_v1 --preprocessing_name=mobilenet_v1`

This triggers many of these:
```
2017-09-11 19:59:25.720547: W tensorflow/core/framework/op_kernel.cc:1192] Out of range: FIFOQueue '_2_prefetc
h_queue/fifo_queue' is closed and has insufficient elements (requested 1, current size 0)
         [[Node: fifo_queue_Dequeue = QueueDequeueV2[component_types=[DT_FLOAT, DT_FLOAT], timeout_ms=-1, _dev
ice="/job:localhost/replica:0/task:0/cpu:0"](prefetch_queue/fifo_queue)]]
INFO:tensorflow:Caught OutOfRangeError. Stopping Training.
INFO:tensorflow:Finished training! Saving model to disk.
```
and finally:
```
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.FailedPreconditionError: input must have 3 channels but input only has 1 channels.
         [[Node: distort_image/distort_color/adjust_saturation/RGBToHSV = RGBToHSV[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](distort_image/distort_color/adjust_saturation/Identity)]]
```

**Comment by csbenk** [comment]
@amirjamez Same here. Trying to train MNIST(as download size is small :P ) using MobileNet and ending up getting that result. I guess we can't train MNIST using Mobilenet as it is, but need to make input mods and first layer mods.

**Comment by csbenk** [comment]
@Zehaos Even if I use lenet as model_name, I get the following error message.

> NotFoundError (see above for traceback): Key LeNet/conv1/weights not found in checkpoint
>  [[Node: save/RestoreV2_3 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_3/tensor_names, save/RestoreV2_3/shape_and_slices)]]

**Comment by csbenk** [comment]
@Zehaos Even if I use lenet as model_name, I get the following error message.

> NotFoundError (see above for traceback): Key LeNet/conv1/weights not found in checkpoint
>  [[Node: save/RestoreV2_3 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_3/tensor_names, save/RestoreV2_3/shape_and_slices)]]

**Comment by akssieg** [comment]
Hi, First I padded the MNIST and coverted it to 32x32. Then ran MobileNet architecture for 1 million iterations.
I got 99% accuracy on test. 
How to deal with this poor accuracy? Does that mean I cannot actually apply it to other data?

**Comment by Zhengyu-Li** [comment]
@akssieg how do you handle the channel problem in Mobilenet? It seems use 3 channels but Mnist only has one...
