### ISSUE TITLE
Can't find the proper output node name

### ISSUE THREAD

**Issue by badlooop** [Zehaos/MobileNet#3]
Hi Zehaos,

First of all, thanks for sharing your works!

In order to run this model on iOS device, I was trying to use freeze_graph.py to freeze your ckpt files, but I can not find the right name of the output node. 

Do you have any idea that what output node I should use to freeze your ckpt file?

Many thanks!

**Comment by Zehaos** [comment]
Hi,

Thanks for using my code. 

You can use tensorboard to inspect nodes in the graph (run train first to get a initial summary), I think the output nope should be 'clone_0/MobileNet/Predictions/Softmax'.

Could you report the inference time if success? Thanks in advance.
