### ISSUE TITLE
问题 OOM when allocating tensor with shape[4,7,7,1024]

### ISSUE THREAD

**Issue by roney123** [Zehaos/MobileNet#30]
我把这个 train_mobilenet_on_imagenet.sh 文件中检测脚本给注释掉了，
现在只跑训练会跑这个错误 ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[64,32,112,112]
然后我修改了 --batch_size=4 ,可以跑起来，但是一会还是会报错 OOM when allocating tensor with shape[4,7,7,1024]
还请大神指导一下。。。。

**Comment by Zehaos** [comment]
显存不够？ 用的Optimizer是？

**Comment by roney123** [comment]
@Zehaos  应该是显存不够吧 用的yellowfin

**Comment by Zehaos** [comment]
@roney123 你的显存多少？ batch_size=4不太可能爆吧。。。

**Comment by roney123** [comment]
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 375.26                 Driver Version: 375.26                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K80           On   | 0000:05:00.0     Off |                    0 |
| N/A   38C    P0    57W / 149W |  10896MiB / 11439MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla K80           On   | 0000:06:00.0     Off |                    0 |
| N/A   49C    P0    73W / 149W |  10871MiB / 11439MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla K80           On   | 0000:88:00.0     Off |                    0 |
| N/A   37C    P0    58W / 149W |  10873MiB / 11439MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla K80           On   | 0000:89:00.0     Off |                    0 |
| N/A   52C    P0    72W / 149W |  10871MiB / 11439MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

**Comment by roney123** [comment]
我也很纳闷，

**Comment by Zehaos** [comment]
@roney123 额，你这个机器有别人在用吧？tf默认会占满。 你现在单卡只剩500MB不到。

**Comment by roney123** [comment]
额 没有吧，就我自己在用啊

**Comment by roney123** [comment]
确实  我的机器都可低  2MiB / 11439MiB   就这个高，，mmp明天换个机器做，而且我又跑了一下，，这次还可以，哈哈

**Comment by Zehaos** [comment]
哈哈哈哈

**Comment by roney123** [comment]
谢谢大神了

**Comment by Zehaos** [comment]
@roney123 如果训练完能report下结果吗？谢谢了

**Comment by roney123** [comment]
OK,哈哈

**Comment by roney123** [comment]
大神 训练时global step 一直为0 是正常的吗 不是应该一直在增加吗？
INFO:tensorflow:global step 0: loss = 2.0650 (0.839 sec/step)
INFO:tensorflow:global step 0: loss = 2.0737 (0.833 sec/step)
INFO:tensorflow:global step 0: loss = 2.0824 (0.839 sec/step)
INFO:tensorflow:global step 0: loss = 2.1162 (0.829 sec/step)
INFO:tensorflow:global step 0: loss = 1.9480 (0.835 sec/step)
INFO:tensorflow:global step 0: loss = 2.1134 (0.847 sec/step)
INFO:tensorflow:global step 0: loss = 2.1269 (0.837 sec/step)
我的都是这样的，我跑了一遍例子也是这样

**Comment by Zehaos** [comment]
正常的，因为yollowfin hold了自己的global step，我还没什么办法把他拿出来。

**Comment by roney123** [comment]
哦哦  好吧 我说我没改啥，怎么这样了

**Comment by Lixueqingqq** [comment]
大神我也遇到了这样的问题：我用tensorflow object detection api 中的train.py  设置的参数为
 --logtostderr \
    --pipeline_config_path=D:/My_project/jiezouzhe/faster_rcnn_resnet50_pets.config \     
    --train_dir=D:/My_project/jiezouzhe/train_log2 \     
    --num_clones=2 \      
    --ps_tasks=1
训练90张图片，batchsize=2,我两块GPU,GPU型号：GTX1080 运行时（totalMemory: 11.00GiB freeMemory: 9.10GiB）
也报了同样的错：
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[1,1080,1920,3]
	 [[Node: ToFloat = Cast[DstT=DT_FLOAT, SrcT=DT_UINT8, _device="/job:localhost/replica:0/task:0/device:CPU:0"](ExpandDims_4)]]
而且不是一开始出错，我是跑了34步后出错的，很崩溃啊，不知道问题出在哪儿

**Comment by wangyazhao001** [comment]
我也是同样的问题，请问怎么样才能解决啊 ？

**Comment by Davidrjx** [comment]
我也遇到了，在GTX1080ti环境下

**Comment by daodaoawaker** [comment]
@Lixueqingqq 你好，请问你后来解决了吗，我也是遇到了这个问题卡了很久，能分享下怎么解决的吗

**Comment by roney123** [comment]
我感觉应该是显存不够了，我当初出现这个问题是因为和别人共用一个gpu，所以我可用的显存很小，出现这个问题了，可以用`nvidia-smi` 看看显存大小

**Comment by daodaoawaker** [comment]
@roney123 是GPU资源耗尽的问题，但是我的GPU是NVIDIA Quadro P2000 5G显存，就我自己用，而且我也按网上说的加了一下代码对GPU进行了限制，结果还是这个问题
config = tf.ConfigProto()
config.gpu_options.allocator_type = 'BFC'
config.gpu_options.per_process_gpu_memory_fraction = 0.80
sess = tf.Session(config=config)
K.set_session(sess)

**Comment by Davidrjx** [comment]
那应该就是代码问题，导致显存溢出了
