### ISSUE TITLE
gpu大小

### ISSUE THREAD

**Issue by wangxiaoyaner** [Zehaos/MobileNet#31]
你好，你训练的时候（batch_size=128)是用到了２块GTX1060么？我用泰坦x时提示我显存不够

**Comment by wangxiaoyaner** [comment]
ResourceExhaustedError。恩１０８０的话有１６Ｇ了。谢谢你！

**Comment by Zehaos** [comment]
单卡显存才是瓶颈，所以8G是可以batch_size = 128的，应该是别的问题。再试试别的optimizer，当时没用yollowfin。

**Comment by wangxiaoyaner** [comment]
问问题时，我跑的是官方源码，使用了你的代码之后能正常工作！再次感谢。

**Comment by wangxiaoyaner** [comment]
你好，我想咨询一下你的训练时间，跑到８０万步的时候你大概用了多久。我个人跑的时候发现需要１～１.3秒每步。

**Comment by Zehaos** [comment]
大概2.8h一个epoch, 你算下你一个epoch的时间。

**Comment by kyuusaku** [comment]
@wangxiaoyaner 我用官方源码的时候，也出现了显存不够的问题。
